name: Deploy Reflex App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Reflex Cloud
        uses: reflex-dev/reflex-deploy-action@v2
        with:
          auth_token: ${{ secrets.REFLEX_AUTH_TOKEN }}
          project_id: ${{ secrets.REFLEX_PROJECT_ID }}
          python_version: "3.12"
          # app_directory: "."
          # extra_args: "--env OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"
